spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/travel
    username: postgres
    password: user123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8080}
  servlet:
    context-path: /travel
    
